name: teacher_app
description: Smart Attendance Teacher Kit - University attendance management system
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  go_router: ^15.1.0
  intl: ^0.20.2
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true